name: wallink_v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.0
  sqflite: ^2.3.0
  path: ^1.9.0
  sqflite_common_ffi: any
  google_fonts: ^5.0.0
  shared_preferences: ^2.0.8
  carousel_slider: ^4.2.1
  fluttertoast: ^8.0.7
  flutter_slidable: ^3.1.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  google_nav_bar: ^5.0.6
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpeg"

flutter:
  uses-material-design: true
  assets: 
    - assets/intro.png 
    - assets/intro2.png
    - assets/intro3.png
    - assets/no_data.png
  fonts :
    - family: samsung_one
      fonts: 
        - asset: assets/fonts/SamsungOne-400.ttf
        - asset: assets/fonts/SamsungOne-700.ttf
          weight: 700
    - family: sharp
      fonts:
        - asset: assets/fonts/SamsungSharpSans-Bold.ttf

          